### ISSUE TITLE
Add code folding

### ISSUE THREAD

**Issue by lcolladotor** [Bioconductor/BiocStyle#1]
Hi,

Jim Hester just commented at the `knitrBootstrap` package https://github.com/jimhester/knitrBootstrap/pull/68#issuecomment-199293180 that the new `rmarkdown` release supports code folding as described at http://blog.rstudio.org/2016/03/21/rmarkdown-v0-9-5/.

I don't know how much work it would be, but it'd be great if `BiocStyle` also supported code folding. For example, the current test does not work:

``````
---
title: "test"
author: "L Collado-Torres"
date: "`r doc_date()`"
output: 
  BiocStyle::html_document:
    code_folding: hide
---

```{r}
plot(1:10, 1:10)
```
``````

Best,
Leo

```
> packageVersion('rmarkdown')
[1] ‘0.9.5’
> packageVersion('BiocStyle')
[1] ‘1.8.0’
```

**Comment by aoles** [comment]
Hi Leo,
thank you for your suggestion! This will require some updates to the `BiocStyle::html_document` function and the html template, but should be feasible. I will look into this.

Cheers,
Andrzej

**Comment by lcolladotor** [comment]
Awesome, thanks for looking into this Andrzej!

**Comment by aoles** [comment]
Hi Leo,
I'm pleased to inform you about the progress on enabling code folding in BiocStyle. This functionality, along with all the rest of recent additions to rmarkdown, plus some additional features, will be available in the new implementation of BiocStyle. 

I'm currently working on the new format for HTML documents, which I will be announcing in a few weeks time. But you can already have a foretaste of it: check out the `BiocStyle::html_document2` function! It accepts all the options that `rmarkdown::html_document` does. (Use with caution though: it's still experimental..)

Cheers,
Andrzej

**Comment by lcolladotor** [comment]
Sorry for missing this earlier Andrzej!

Thank you for adding code folding =)
