### ISSUE TITLE
Margin notes and other style

### ISSUE THREAD

**Issue by witszymanski** [Bioconductor/BiocStyle#101]
Cześć Andrzej! 

I am having a styling issue and would be great if you could help me. In an older version of the BiocStyle, the references and footnotes were going to the margin, which is exactly what I want:
![image](https://user-images.githubusercontent.com/15866068/202473711-1784aaf2-c10b-4cf3-a3d1-950c8cdc91b9.png)

Now, when I take your code and try to recreate it, I get the footnotes at the bottom of the document. 
![image](https://user-images.githubusercontent.com/15866068/202473379-0f94c40a-f250-4739-8645-20772795fa4c.png)
![image](https://user-images.githubusercontent.com/15866068/202473455-f0a0e60f-a4db-48d0-86c6-f483dc263766.png)

Is it possible to force it to the margin? 

Here is the output of sessionInfo() on the system on which this document was compiled:
```

## R version 4.1.3 (2022-03-10)
## Platform: x86_64-pc-linux-gnu (64-bit)
## Running under: Ubuntu 22.04.1 LTS
## 
## Matrix products: default
## BLAS:   /usr/lib/x86_64-linux-gnu/blas/libblas.so.3.10.0
## LAPACK: /usr/lib/x86_64-linux-gnu/lapack/liblapack.so.3.10.0
## 
## locale:
##  [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C              
##  [3] LC_TIME=de_DE.UTF-8        LC_COLLATE=en_US.UTF-8    
##  [5] LC_MONETARY=de_DE.UTF-8    LC_MESSAGES=en_US.UTF-8   
##  [7] LC_PAPER=de_DE.UTF-8       LC_NAME=C                 
##  [9] LC_ADDRESS=C               LC_TELEPHONE=C            
## [11] LC_MEASUREMENT=de_DE.UTF-8 LC_IDENTIFICATION=C       
## 
## attached base packages:
## [1] stats     graphics  grDevices utils     datasets  methods   base     
## 
## other attached packages:
## [1] BiocStyle_2.22.0
## 
## loaded via a namespace (and not attached):
##  [1] bookdown_0.27       digest_0.6.29       R6_2.5.1           
##  [4] jsonlite_1.8.0      magrittr_2.0.3      evaluate_0.15      
##  [7] highr_0.9           stringi_1.7.6       rlang_1.0.2        
## [10] cli_3.3.0           rstudioapi_0.13     jquerylib_0.1.4    
## [13] bslib_0.3.1         rmarkdown_2.14      tools_4.1.3        
## [16] stringr_1.4.0       xfun_0.31           yaml_2.3.5         
## [19] fastmap_1.1.0       compiler_4.1.3      BiocManager_1.30.18
## [22] htmltools_0.5.2     knitr_1.39          sass_0.4.1


```

**Comment by grimbough** [comment]
Hi @witszymanski ,

I think this is because you're now using a newer version of Pandoc.  (RStudio update this periodically if you're running that).  This has altered some of the tags placed around footnotes, which BiocStyle uses to detect them and move them to the side margin.  I made a fix for this in https://github.com/Bioconductor/BiocStyle/pull/95/commits/b53182f3fe40c7825a1e185a17e20b4d9b470845 but it hasn't made it into BiocStyle yet.

You can try using my fork of BiocStyle at https://github.com/grimbough/BiocStyle which includes the patch.  It'd be good to know if it works.

**Comment by witszymanski** [comment]
It worked like a charm!
![image](https://user-images.githubusercontent.com/15866068/202700185-a39042e5-9ff8-4d50-aaf0-222fc99c4020.png)

Thank you very much!

**Comment by aoles** [comment]
Fixed in https://github.com/Bioconductor/BiocStyle/pull/95.
