### ISSUE TITLE
pdf_document2 breaks with `A = 12`

### ISSUE THREAD

**Issue by rdiaz02** [Bioconductor/BiocStyle#14]
```
---
output: 
  BiocStyle::pdf_document2:
    keep_tex: true 
---

# Something

If I write `A = 1` , the 1 is missing (from pdf_decoment2 in BiocStyle).

If I write `A = 12` this breaks "BiocStyle::pdf_document2" (but
not "BiocStyle::pdf_document", nor "bookdown::pdf_document2")

```

Trying to tex the file, it seems to be related to the soul package:

```
./file1.tex:121: Package soul Error: Reconstruction failed.

See the soul package documentation for explanation.
Type  H <return>  for immediate help.
 ...                                              
                                                  
l.121 If I write \texttt{A\ =\ 12}
                                   this breaks ``BiocStyle::pdf\_document2''
? 
```

**Comment by rdiaz02** [comment]
In general, it seems that (except for very short expressions), trying to get monospaced text fails, regardless of whether we use one, two, or three back ticks.
```
``something = something else ``
`something = another thing`  
```

**Comment by aoles** [comment]
Hi Ramon,
thank you for reporting this issue! As you have noticed correctly, it's related to the *soul* package. More specifically, *soul* doesn't like the `'\ '` spaces, which appear in monospaced font rendered by pandoc. I've just committed a quick fix for this.

Thanks for your other bug reports, too. I'm currently out of office, so it might take a while until I review and respond to them.

Cheers,
Andrzej

**Comment by rdiaz02** [comment]
Great, thanks! Just checked and it is working.
