### ISSUE TITLE
Suggestion: spell Warnings with a capital

### ISSUE THREAD

**Issue by lgatto** [Bioconductor/BiocStyle#16]
The `\warning` macro is nice to keep warning or important messages consistent throughout different vignette. I was wondering what you thought about capitalising the first Warning word in the paragraph. IMHO, it does look a bit weird that a paragraph suddenly starts with a lower case.

**Comment by aoles** [comment]
Dear Laurent,

thank you for your suggestion. Indeed, it makes probably more sense to have the default opening word capitalized in general for all types of messages (i.e., warnings, comments, and fixme). I've updated the BiocStyle v.2 devel version accordingly, see https://github.com/Bioconductor/BiocStyle/commit/97075c056b7b4621322f467417af4c4c104d8c6a.

In fact, in BiocStyle v.2 the default "warning" word can be overridden by an optional argument, e.g. `\warning[Important]{common pitfalls}`. I've documented this feature in the vignette.

Cheers,
Andrzej
