### ISSUE TITLE
knitr should be moved from Suggests to Imports.

### ISSUE THREAD

**Issue by siddharthab** [Bioconductor/BiocStyle#2]
In using bioc-devel without knitr installed, and trying to install BiocStyle, I get the following error:

```
* installing *source* package ‘BiocStyle’ ...
** R
** inst
** preparing package for lazy loading
Error in loadNamespace(name) : there is no package called ‘knitr’
Error : unable to load R code in package ‘BiocStyle’
ERROR: lazy loading failed for package ‘BiocStyle’
* removing ‘/usr/local/google/home/sidb/lib/R/library/BiocStyle’

The downloaded source packages are in
        ‘/tmp/RtmpQlYKcL/downloaded_packages’
Updating HTML index of packages in '.Library'
Making 'packages.html' ... done
Warning message:
In install.packages(pkgs = doing, lib = lib, ...) :
  installation of package ‘BiocStyle’ had non-zero exit status
```

**Comment by aoles** [comment]
Thank you for reporting this! In fact, the dependency on *knitr* was not intended, as it is in possible to use *BiocStyle* with non-knitr .Rnw files. In that case you might don't want to and you don't need to install *knitr*.

I've fixed this in https://github.com/Bioconductor/BiocStyle/commit/cc9d9697561af1a5f952d9205ec86e8fce7949b9 (version 2.1.12)
