### ISSUE TITLE
Affiliation for single author

### ISSUE THREAD

**Issue by lgatto** [Bioconductor/BiocStyle#21]
Could you clarify how to define an affiliation for a single author `html_document2`. I tried 
```
author: my name
affiliation: my affiliation
```
but the latter is ignored.

I also tried
```
author:
  - name: my name
  - affiliation: my affiliation
```
but then it print *my name and NULL*.

```
author:
  - name: my name
    affiliation: my affiliation
```

fails when building the package.

**Comment by aoles** [comment]
Hi Laurent,
the proper syntax for defining author affiliations is the last one. It's supposed to work for both `pdf_document2` and `html_document2`. I've just checked that the following document renders fine with BiocStyle v2.3.28. Could you maybe clarify what is the exact error you get?

```
---
title: Title
author:
- name: Author
  affiliation: Affiliation
output:
  BiocStyle::html_document2
---
```

**Comment by lgatto** [comment]
Sorry, it must have been something else that generated the error yesterday. It now works as expected. Thank you for the great work!
![2016-12-22-153042_546x182_scrot](https://cloud.githubusercontent.com/assets/384198/21430573/a9988518-c85b-11e6-8c10-8c0ed5e00817.png)

**Comment by ziyili20** [comment]
Hi Aoles,

Following Laurent's question, is it possible to remove the superscript 1 from this single author, single affiliation situation?  When only one affiliation is included, this symbol 1 seems unnecessary.

Ziyi
