### ISSUE TITLE
CRANpkg links to a mirror instead of the CRAN

### ISSUE THREAD

**Issue by llrs** [Bioconductor/BiocStyle#24]
When using  `CRANpkg("data.table")` it links to the mirror of CRAN at http://cran.fhcrc.org. The mirror itself says:

> Please use the canonical form https://CRAN.R-project.org/package=data.table to link to this page.

While the link CRANpkg produces is [`http://cran.fhcrc.org/web/packages/data.table/index.html`](http://cran.fhcrc.org/web/packages/data.table/index.html). I tried using [`http://cran.fhcrc.org/packages=data.table`](http://cran.fhcrc.org/packages=data.table) but it couldn't be resolved.

The FAQ question [What is CRAN?](https://cran.r-project.org/doc/FAQ/R-FAQ.html#What-is-CRAN_003f) explicitly says:

> Please always use the URL of the master site when referring to CRAN. 

I know you are aware of this, but I couldn't find the reason behind this decision. Why does the BiocStyle link to FHCRC CRAN mirror instead of the recommended master site?

**Comment by aoles** [comment]
Many thanks for drawing our attention to this issue!

I believe there is no real reason why we shouldn't follow the official guidelines and link to the canonical CRAN repository. I will change the links accordingly.

Cheers,
Andrzej

**Comment by mtmorgan** [comment]
Yes, the use of fhcrc was an historical artifact and is no longer relevant.
