### ISSUE TITLE
How does \@ref() work?

### ISSUE THREAD

**Issue by lgatto** [Bioconductor/BiocStyle#26]
Could anyone explain me how the cross-references described [here](http://master.bioconductor.org/packages/devel/bioc/vignettes/BiocStyle/inst/doc/AuthoringRmdVignettes.html#8_cross-references) works/is implemented. 

The reason I am asking is that it works in vignettes compiled with `rmarkdown::render` given a properly formatted header, but it doesn't when creating vignettes as part of a [pkgdown](https://github.com/hadley/pkgdown) site that compiles and includes vignettes:

![2017-05-26-230929_891x151_scrot](https://cloud.githubusercontent.com/assets/384198/26514256/97c3dfb8-4268-11e7-95ff-c7cd5667744f.png)

**Comment by aoles** [comment]
Hi Laurent,
cross references as described in the BiocStyle vignette are implemented by [**bookdown**](https://github.com/rstudio/bookdown). The incompatibility with **pkgdown** appears to be a known issue, see https://github.com/hadley/pkgdown/issues/323.

Cheers,
Andrzej

**Comment by lgatto** [comment]
Thanks!
