### ISSUE TITLE
fig.asp interpretation seems to be flipped

### ISSUE THREAD

**Issue by LTLA** [Bioconductor/BiocStyle#34]
Reading the user guide suggests that the figure aspect ratio is WIDTH/HEIGHT, e.g., a wide figure has a ratio of 2. However, setting something like:

```
<<smallfig, fig.asp=2>>=
plot(1, 1)
@
```

... gives me a tall figure rather than a fat figure. Similarly, setting `fig.asp=0.5` gives me a fat figure rather than a tall figure. Presumably this is not intended?

**Comment by aoles** [comment]
Thanks for drawing my attention to this. `fig.asp` works as intended the same way as the regular knitr argument, i.e. (after knitr documentation)

 >`fig.asp`: (`NULL`; numeric) the aspect ratio of the plot, i.e. the ratio of height/width; when `fig.asp` is specified, the height of a plot (the chunk option `fig.height`) is calculated from `fig.width * fig.asp`.

The confusion comes from the fact that the typical definition of graphics aspect ratio is (according to Google)

> the ratio of the width to the height of an image or screen

which is the exact opposite of how `fig.asp` works.  In the vignette describing LaTeX figure environments available in BiocStyle I use the common definition of "aspect ratio" without making any reference to knitr's `fig.asp`. I will try to improve the documentation to avoid similar confusion in the future.

**Comment by LTLA** [comment]
Cool, thanks.
