### ISSUE TITLE
TOC Chapter headings are small font

### ISSUE THREAD

**Issue by LTLA** [Bioconductor/BiocStyle#35]
In my updated version of the _csaw_ user's guide, using _BiocStyle_ yields a TOC where the chapter headings seem to be of a smaller font than the section headings. They are bold, which is nice, but should the chapter headings be larger than - or at least, of equal size to - the section headings?

**Comment by aoles** [comment]
Thanks, will look into this.

**Comment by LTLA** [comment]
Thanks Andrzej. Funnily enough, I still get the old small font when I set `relative.path=TRUE`.

```{r}
\documentclass{report}

<<style-knitr, eval=TRUE, echo=FALSE, results="asis">>=
BiocStyle::latex(relative.path=TRUE)
@

\begin{document}

\tableofcontents
\newpage

\chapter{Introduction}

\chapter{Epilogue}

\section{Session information}
<<>>=
sessionInfo()
@

\end{document}
```

Presumably something didn't get copied?

**Comment by aoles** [comment]
That's because *Bioconductor2.sty* is copied over by a call to `file.copy` with `overwrite=FALSE`. Just delete the file in your document working dir and recompile.

**Comment by LTLA** [comment]
Ah, okay. Perhaps `overwrite=TRUE` might be more intuitive/expected? Just my two cents.
