### ISSUE TITLE
Deprecation message for latex2 breaks LaTeX

### ISSUE THREAD

**Issue by hpages** [Bioconductor/BiocStyle#36]
Hi Andrzej,

See https://stat.ethz.ch/pipermail/bioc-devel/2017-September/011750.html for the details.

Thanks,
H.

**Comment by aoles** [comment]
Thanks Hervé for troubleshooting this and for drawing my attention to this issue. `BiocStyle::latex2` can be used with either plain *Sweave* or *knitr*, and it seems that the problem occurs only in the latter scenario. I'm not sure what would be the best approach here other than disabling the deprecation message entirely, which is not a perfect solution either. Any ideas? I would like to avoid over-engineering things.

**Comment by hpages** [comment]
I don't have enough insight here to provide advice. I'm confused about whether deprecation messages **in general** would cause a LaTeX error in that scenario, or if it's only the deprecation message issued by `BiocStyle::latex2`. If it's the latter, then disabling `BiocStyle::latex2` deprecation message entirely would be better than the current situation, at least for _knitr_ users (plain _Sweave_ users would loose it though, which is unfortunate). But if it's the former, then of course the issue is more serious and needs a proper solution.

**Comment by aoles** [comment]
Thanks! The problem was caused in first place by LaTeX complaining about undefined `\kframe` environment. As `latex()` provides the missing definition, moving the call to `.Deprecated` after it fixes the issue.

**Comment by hpages** [comment]
Glad you found a fix. Thanks!
