### ISSUE TITLE
LaTeX errors (Dimension too large) in Bioconductor package cosmiq possibly caused by recent changes to BiocStyle::latex()

### ISSUE THREAD

**Issue by hpages** [Bioconductor/BiocStyle#37]
Hi Andrzej,

`R CMD build cosmiq` started to fail on Linux and Mac at some point between Jun 27 (date of last commit to the package) and today:

  https://bioconductor.org/checkResults/3.6/bioc-LATEST/cosmiq/malbec1-buildsrc.html
  https://bioconductor.org/checkResults/3.6/bioc-LATEST/cosmiq/veracruz1-buildsrc.html

This seems to be caused by the recent changes to `BiocStyle::latex()`. If I install the release version of BiocStyle then `R CMD build cosmiq` completes successfully (tested on Linux only).

It is not clear to me if the problem could somehow be addressed by making some adjustments to `BiocStyle::latex()` or if the cosmiq maintainers need to do something on their side to make the `poster.Rnw` vignette compatible with the current `BiocStyle::latex()`.

Any advice would be appreciated.

Thanks,
H.

**Comment by aoles** [comment]
Thanks Hervé! BiocStyle was developed primarily for authoring package vignettes and similar documentation. Due to some layout constraints it doesn't support other scenarios such as posters or presentations. I'm not sure whether it is feasible to provide a general solution to this issue in BiocStyle, this will require additional troubleshooting and investigation. For now I would suggest *cosmiq* maintainers to adjust their document, e.g. use the legacy `BiocStyle::latex_old()`.

Cheers,
Andrzej

**Comment by hpages** [comment]
I replaced `BiocStyle::latex()` with `BiocStyle::latex_old()` in their document. We'll see how it goes. Thanks!

**Comment by aoles** [comment]
Thanks Hervé for the update. Please note that the original plan is to defunct `BiocStyle::latex_old()` after the release. I've looked into the offending vignette and it seem that the styling of the poster could be also relatively easily achieved by copying the relevant parts of the style file into their source document. So this might be a long term solution if I don't manage to provide a general compatibility fix for the new style.

**Comment by hpages** [comment]
Hi Andrzej, using `BiocStyle::latex_old()` instead of `BiocStyle::latex()` did the trick. Thanks!  H.

**Comment by hpages** [comment]
Also thanks for the heads up about your plans for `BiocStyle::latex_old()`. Will forward to the cosmiq folks.

**Comment by aoles** [comment]
You're welcome! I've mentioned this before in the BioC devel mailing list and the support forum [announcements](https://support.bioconductor.org/p/98942/).
