### ISSUE TITLE
Figures aspect ratio

### ISSUE THREAD

**Issue by lgatto** [Bioconductor/BiocStyle#4]
The different figure environments are really nice. There are however cases where I would like to display a large (as in not `smallfigure`) square figure. I tried using `fig.asp = 1`, but without effect. Is this a desired behaviour?

I am running `BiocStyle` `2.1.7`.

**Comment by aoles** [comment]
Hi Laurent,
many thanks for reporting this. This is indeed not desired, I will fix it in the following update. In the meantime, you can always override the default figure aspect ratio by specifying both `fig.width` and `fig.height` code chunk options.

**Comment by lgatto** [comment]
Thanks Andrzej. There's no urgency for now, so I'll wait until it is fixed.

**Comment by aoles** [comment]
Hi Laurent,
thanks for your patience! I've just fixed setting figure aspect ratio via `fig.asp` chunk option. I've also added a paragraph to the *Bioconductor LaTeX Style 2.0* vignette documenting this feature.

**Comment by lgatto** [comment]
Thank you, Andrzej. Your work is much appreciated!
