### ISSUE TITLE
First sentence of figure caption ending with a full stop, no line break?

### ISSUE THREAD

**Issue by LTLA** [Bioconductor/BiocStyle#40]
Is it possible to provide this as an option? The current scheme (line break with no full stop) makes sense for short first sentences, but it looks odd when the first sentence is longer. This is the case for many of my figures where the description for a figure takes up one sentence that isn't easily broken up.

To be clear, I wouldn't require this as an option for each individual figure; a global setting would be sufficient, as I write my figure captions in the same way across any single document.

**Comment by aoles** [comment]
Thanks Aaron for pointing this out! In fact, we already have this option for pdf output, see the `titlecaps` argument to `pdf_document` and `latex`. I will add it to `html_document` too.
