### ISSUE TITLE
Width in code chunk is causing a wrapper to appear in a vignette

### ISSUE THREAD

**Issue by FelixErnst** [Bioconductor/BiocStyle#41]
Hi,

have a look at https://github.com/Bioconductor/Contributions/issues/607#issuecomment-364676362.

Inside the vignette a longer character is displayed, which cannot be shortened, causing a wrapper with a horizontal scrollbar to appear. This might be due to the fact, that the character does not contain any space and only the letters ".><"

@hpages suggest opening an issue and or asking for help on this. I don't, what I can do on my end to resolve the issue. Please advice.

**Comment by aoles** [comment]
Hi Felix,

thanks for your feedback. BiocStyle document body width is fixed and does not scale with the document. This is so on purpose as the idea behind it is that the appearance of PDF and HTML output is possibly similar. It is quite unlucky that ` tRNA_str` does not fit the default width. Unfortunately, setting different width is currently not supported. Please note that for me the line simply gets wrapped without any scrollbar, so the exact behavior might be browser-dependent.

Cheers,
Andrzej

![tsp1](https://user-images.githubusercontent.com/6545356/36089871-4215c830-0fde-11e8-9726-3494ac52b120.png)
