### ISSUE TITLE
Code formatting overflows in magin note

### ISSUE THREAD

**Issue by lgatto** [Bioconductor/BiocStyle#5]
As shown below, the `\Rcode{times = 10}` inline code formatting somehow overflows in the side margin. 

![2016-06-26-005728_978x322_scrot](https://cloud.githubusercontent.com/assets/384198/16359741/0a02061e-3b39-11e6-8969-b858aea34368.png)

If I remove the formatting (remove `\Rcode`), the margin note displays as expected

![2016-06-26-005959_975x300_scrot](https://cloud.githubusercontent.com/assets/384198/16359747/531f7606-3b39-11e6-8024-51e6666596f3.png)

**Comment by aoles** [comment]
That's kind of weird, I'm not sure how this can happen and I was also not able to reproduce it. Could you maybe share some minimal example intermediate .tex source file which illustrates this issue? Don't forget to include the BiocStyle version number. Thanks!

**Comment by lgatto** [comment]
Very weird indeed. The file/lines that produced this is are here https://github.com/lgatto/pRoloc/blob/7efa415ebdb05bcf24fa81a7f33e3e9a4cef83d2/vignettes/pRoloc-tutorial.Rnw#L856-L860. The corresponding `tex` file is [here](http://proteome.sysbiol.cam.ac.uk/lgatto/files/pRoloc-tutorial.tex).

It's not a minimal reproducible example - I'll try to prepare one later. In the meantime, I have *fixed* it by rephrasing my sentence a bit.

**Comment by aoles** [comment]
Thank you Laurent for spotting and for reporting this! I was able to reproduce the described behavior. It's rather unexpected and I'm surprised to see this side effect. I will need to investigate it further, maybe it is related to the other issues with side notes reported in https://github.com/Bioconductor/BiocStyle/issues/3.

**Comment by lgatto** [comment]
Thanks, Andrzej for following up this and issue #3.
