### ISSUE TITLE
mobile-friendly vignettes

### ISSUE THREAD

**Issue by lwaldron** [Bioconductor/BiocStyle#59]
Could html vignettes be made more mobile-friendly? For example, attached is a screenshot of the [BiocStyle vignette](http://bioconductor.org/packages/release/bioc/vignettes/BiocStyle/inst/doc/AuthoringRmdVignettes.html) (Scrolled to the start of section 1) on a simulated iPhone X display (375x812); the text ends up in a very narrow column.

![biocstyle_iphonex](https://user-images.githubusercontent.com/639942/51530557-85e82c80-1e3b-11e9-9d7d-26cd2312a5ef.png)

**Comment by grimbough** [comment]
These improvements were added in #67
