### ISSUE TITLE
fig.cap containing a dot

### ISSUE THREAD

**Issue by FelixErnst** [Bioconductor/BiocStyle#61]
When I use a code chunk like this and knit a html document the output will by formated incorrectly. The dot in `5.8S` functions as a line break.

```
```{r plot1, fig.cap="Heatmap showing RiboMethSeq scores for 2'-O methylated positions on the 5.8S rRNA."}
# some plotting going on
```
![image](https://user-images.githubusercontent.com/17824332/58563008-a7fb1c80-822a-11e9-91e2-4cc80d2cc591.png)

Escaping with `\\` does not change the behavior.

Any help or advice how to handle this case? Thanks.

**Comment by aoles** [comment]
Thanks for your feedback!

The observed behavior is a consequence of the way how the figure title is extracted. This is done in [`caption_titles()`](https://github.com/Bioconductor/BiocStyle/blob/master/R/html_document.R#L220) by performing a splitting on the first occurred `.` without considering the context. This shortcoming could be improved by looking for a dot followed by white character, as already [implemented for the PDF output](https://github.com/Bioconductor/BiocStyle/blob/master/inst/resources/tex/Bioconductor.sty#L447). Feel free to contribute with a PR.

Cheers,
Andrzej
