### ISSUE TITLE
parnotes rev. 2 / custom definition of \parnotemarkfmt

### ISSUE THREAD

**Issue by kevinrue** [Bioconductor/BiocStyle#7]
Dear Maintainer,

I believe a recent release of parnotes (rev. 2, https://www.ctan.org/pkg/parnotes) is causing problem with Bioconductor LATEX Style 2.0.

While a day ago Travis CI was perfectly happy compiling my package currently hosted on GitHub, the same Travis configuration now returns the following error:

```
! Package parnotes Error: Cannot use custom definition of \parnotemarkfmt
(parnotes)                in parnotes rev. 2 or later. Use \theparnotemark
(parnotes)                and \parnotecusmarkfmt instead.
```

I can see in your vignette that parnotes is one of the LaTeX packages that is loaded and used by this style.
I'll appreciate if you could look into the issue, and update your code accordingly.

Thank you very much for the great work
Kevin

**Comment by kevinrue** [comment]
It may be relatively obvious, but I forgot to say that to replicate the issue, you'll have to update parnotes to the latest version. 
Just in case it might help you replicate the issue, the way I update parnotes (and other required packages) to the latest version on Travis was:

    tlmgr install bera nowidow parnotes marginfix

Here is my GitHub [.travis.yml](https://github.com/kevinrue/tSVE/blob/master/.travis.yml) if useful

Apparently, there is no TexLive command to install past releases of a LaTeX package. So I think my Travis builds will be stuck as long as the Bioconductor LATEX Style 2.0 uses \parnotemarkfmt

No rush though, I can perfectly develop and test locally in the meantime.

Best,
Kevin

**Comment by aoles** [comment]
Hi Kevin,
thanks again for spotting and for reporting the issue with updated _parnotes_. You should now be able to compile your vignettes which use _BiocStyle_ devel. I can introduce the bugfix in release as well, if necessary.

Cheers,
Andrzej

**Comment by kevinrue** [comment]
It's alright (Travis CI did most of the spotting!), thanks for the fix, I already found how to tell Travis CI to get packages from the devel branch of BioC, I'll take it from here ;)

**Comment by kevinrue** [comment]
It's alright (Travis CI did most of the spotting!), thanks for the fix, I already found how to tell Travis CI to get packages from the devel branch of BioC, I'll take it from here ;)

**Comment by kevinrue** [comment]
Dear Andrzej,
I just tried building again my code on Travis CI following your recent bug fix (telling Travis to install BiocStyle using `devtools::install_github()`. I tested on my own laptop and this correctly installed BiocStyle/2.1.23 ) Also, on my machine, R CMD check and BiocCheck both complete successfully.

Anyway, the bottom line is that the build failed (with a different LaTeX-related error message), and I don't know whether this is something I can fix, or something else related to how BiocStyle produces files.
Would you mind having a quick look at the end of my [Travis Build Report](https://travis-ci.org/kevinrue/TVTB/jobs/151566227) and let me know what you think?

Another option, if you feel like it, would be to clone my [GitHub repository](https://github.com/kevinrue/TVTB) and run R CMD check on your machine, so that you could have access to the full log produced during LaTeX compilation. 

Anyway, I will keep investigating the issue myself, but any kind of advice is welcome!
Best,
Kevin

**Comment by aoles** [comment]
Dear Kevin,
I could reproduce the error locally and I will follow up on it.

Cheers,
Andrzej

**Comment by kevinrue** [comment]
"Great" to hear that you could reproduce the issue.
I also "managed", just a minute ago, to make R CMD build crash on my Macbook.
The trick was to update my LaTeX packages (`sudo tlmgr update --all`).
Which means I'm not sure which package the problem is coming from now!

Thanks for investigating!

**Comment by kevinrue** [comment]
Dear Andrzej,

I apologise in advance for asking an independent question in this thread, but...

Do you know how to insert a `\newpage` statement before the Table of Content, when writing an Rmd vignette? Is that something that is hard-coded in the template file? I can see the `\newpage` statement in your [LatexStyle2.Rnw](https://github.com/Bioconductor-mirror/BiocStyle/blob/master/vignettes/LatexStyle2.Rnw#L52) file before the table of content, but I do not know how to make that happen in my Rmd file where the bibliography is handled by the YAML metadata section. To illustrate my point, I invite you to have a quick look at my [Introduction.Rmd](https://github.com/kevinrue/TVTB/blob/master/vignettes/Introduction.Rmd) YAML header.

All the best,
Kevin

**Comment by aoles** [comment]
Hi Kevin,

see the `toc_newpage` option to pdf_document2. To start the TOC on a new page, modify your YAML header to include the following.

```
output: 
    BiocStyle::pdf_document2:
      toc_newpage: true
```

**Comment by kevinrue** [comment]
Awesome thanks! Anywhere I can find a list of those options, to avoid bothering you in the future?
Cheers
Kevin

**Comment by aoles** [comment]
These options are relatively new and therefore not properly documented yet. I will update the documentation in the next few weeks, and also add another vignette describing the use of the new style in Rmd documents.

Cheers,
Andrzej

**Comment by aoles** [comment]
Hi Kevin,
It seems that there is some remaining issue with the new version of _parnotes_, and possibly an interaction with another LaTeX package. Things work just fine with the previous version of _parnotes_, but once I switch to _parnotes_ v.2 the document stops compiling. Such beasts are hard to debug, and so far I was unable to boil this down to a MWE demonstrating the problem.

Cheers,
Andrzej

**Comment by kevinrue** [comment]
Thanks for investigating, I will bring this up to the maintainer of parnotes, to see what they think of it.

In the meantime, can you tell me if and how you managed to revert to the previous release of parnotes, so that I can at least build locally? The [suggestions](http://tex.stackexchange.com/questions/31886/historical-stable-version-archive-of-packages) are still a bit confusing to me, and I am currently stuck with parnotes rev. 2.

Also, is this parnotes update going to be an issue for the next release of BioC ? I suppose that at the moment the BioC nightly build uses an installation of parnotes rev. 1, and that at some point packages using the Bioconductor LATEX Style 2.0 will be hit by the update as well?

Thanks for your time!

**Comment by kevinrue** [comment]
Hi Andrzej,

I think you will be happy to read that the parnotes maintainer solved the [issue]( https://github.com/chelh/LaTeX-parnotes/issues/1#issuecomment-239894947) in no time :)

How about closing this issue when the next parnotes release including the fix becomes available?
All the best, and thanks a lot for your time and help again.
Kevin

**Comment by aoles** [comment]
Hi Kevin,

indeed, that's great news! Many thanks for communicating with the maintainer of _parnotes_ and for your help in resolving the issue.

Cheers,
Andrzej

**Comment by chelh** [comment]
I've released the new version of `parnotes` to CTAN as an update without an announcement. Thanks for reporting this issue to me.

**Comment by aoles** [comment]
Awesome, many thanks Chelsea for your prompt update of _parnotes_!
