### ISSUE TITLE
pdf_document: cannot add includes

### ISSUE THREAD

**Issue by renozao** [Bioconductor/BiocStyle#8]
I believe there is a bug in `pdf_document` and `pdf_document2`, where includes are concatenated:

```R
includes$in_header = c(includes$in_header, inc)
```
should be

```R
includes$in_header = c(includes$in_header, inc$in_header)
```

**Comment by aoles** [comment]
Thank you for spotting and for reporting this! I've updated `pdf_document` and `pdf_document2`, both in release and devel. Please let me know whether the bugfix resolved your issue.
