### ISSUE TITLE
Error in if (is.na(options$out.width.px)) argument is length zero

### ISSUE THREAD

**Issue by emiliesecherre** [Bioconductor/BiocStyle#81]
Hello !
My .Rmd file header is 

`title: 'Mypkg'
author: "Emilie"
package: mypkg
output:
    BiocStyle::html_document
vignette: >
    %\VignetteIndexEntry{mypkg}
    %\VignetteEngine{knitr::rmarkdown}
    %\VignetteEncoding{UTF-8}

```{r style, echo = FALSE, results = 'asis'}
BiocStyle::markdown()
````

Though, when the r chunk above is executed, this error occur :
`Error in if (is.na(options$out.width.px)) options$out.width.px = options$fig.width * argument is length zero Calls: <Anonymous> ... process_group.block -> call_block -> as.strict_list -> hook`

How can i fix that ?

**Comment by grimbough** [comment]
Please update your version of BiocStyle with:

```r
BiocManager::install('BiocStyle')
```

The problem should then go away.  This assumes you're using the latest version of R (4.0) and Bioconductor (3.11).

**Comment by emiliesecherre** [comment]
Thx, but now a new error occur : i can't use library(mypkg) in a r chunk (error : there is no package called "mypkg"). 

When i run R CMD , the error is 
`Quitting from lines 60-64 (HowToUse.Rmd) 
   Error: processing vignette 'HowToUse.Rmd' failed with diagnostics:
   Bad request, response code 503
   --- failed re-building 'HowToUse.Rmd'`

With lines 60-64 : 
```{r pathenrich}
data(genes)
data(meta)

listr=path_enrich("REAC", meta, genes)
```

**Comment by grimbough** [comment]
Running `library(mypkg)` assumes that you have installed a package called "mypkg".  If that's not the case then you'll get the error you're seeing.

The examples in the BiocStyle vignette assume you're using the package to style your own vignette in a package - in this case your own package should be called "mypkg" or more likely you should substitute "mypkg" in the Rmd header for the actual name of your own package.  You'll also need to make sure you've installed this new package at least once.

If you're writing a stand-alone Rmd file and just want to use the styling from BiocStyle then you can omit the "mypkg" parts from the header.

If that doesn't help then I think you probably need to provide some more context for the document you're trying to create.

**Comment by emiliesecherre** [comment]
I'm trying to style my package's vignette using BiocStyle. I renamed the 'title' section of the header and the Rmd file using my package's name. Then, should i install my own package ?

**Comment by grimbough** [comment]
Assuming you're working in RStudio, if you're pressing the 'knit' button to compile your vignette you'll need to install the package beforehand.  This only needs to be done once, then the package will be in your library.

It might also be useful to take a look at how some other packages have formatted their header - copying other peoples' examples is normally my go to solution for figuring things like this out.  You can find lots of instances here on Github, for example the DelayedArray vignette is at https://github.com/Bioconductor/DelayedArray/blob/master/vignettes/02-Implementing_a_backend.Rmd

**Comment by emiliesecherre** [comment]
I'll try to install my package then, thank you !

**Comment by grimbough** [comment]
Hopefully this is resolved.  Please re-open if not.
