### ISSUE TITLE
Figures in html_document2

### ISSUE THREAD

**Issue by lgatto** [Bioconductor/BiocStyle#9]
Are there, or will there by different types of figures (regular, small, wide) in the html style, like there is in latex2?

**Comment by aoles** [comment]
Hi Laurent,
the three types of figures known from `pdf_document2` can also be used in `html_document2`. You can specify them with `fig.small` and `fig.wide` code chunk options, as in the following example. Soon there will be a proper vignette documenting the features of the new html style.

    ---
    title: "Figures demo"
    author: "Andrzej Oleś"
    date: '`r doc_date()`'
    output:
      BiocStyle::html_document2
    ---
    
    ```{r fig-regular, fig.cap="Regular figure"}
    plot(cars)
    ```
    
    ```{r fig-wide, fig.cap="Wide figure. A plot produced by a code chunk with option `fig.wide=TRUE`.", fig.wide=TRUE}
    plot(cars)
    ```
    
    ```{r fig-small, fig.cap="Small figure. A plot produced by a code chunk with option `fig.small=TRUE`.", fig.small=TRUE}
    plot(cars)
    ```

**Comment by lgatto** [comment]
Thanks!
